### ISSUE TITLE
Divorce the GUI!

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/meqtrees-timba#66]
As we move to KERN-7, there are many Qt issues to be resolved. Therefore I suggest we break out the browser into a separate package, ``meqtrees-browser``, leaving zero Qt dependencies in ``meqtrees-timba``. Work on porting the browser can proceed at its own pace then.

This should not be hard. The entirety of the browser code is under ``PyApps``. We just need to retain the non-browser bits in ``PyApps``. The ``meqtrees-pipeliner``script and all its dependencies, mequtils, ``PyApps/src/Meq``, pynodes are the ones that come to mind.

**Comment by bennahugo** [comment]
Ok, I have already done some work towards this as is currently released - qt4 will be used if and only if it is on the system. Otherwise, the drop in signal events notification will take the president. So in principle, you should be able to move the files without much pain.

I think this affects @twillis449 so just tagging him in here.

**Comment by bennahugo** [comment]
The only issue is the Purr / kittens stuff also technically needs qt4. So maybe pyqt4 can just be added as optional dependency here?

**Comment by twillis449** [comment]
I'll survive. :) 

@o-smirnov - here's a couple of actual blockages - in Plugins these three pieces of code seem to need a complete update: array_browser.py, parmfiddler.py, and TableInspector.py These scripts all have some dependency on QTable. As far as I can see QTable has not been part of PyQt since PyQt3, so how its even worked with PyQt4 is beyond me. It probably needs to be replaced by QTableWidget but  QTableWidget has some different API calls to QTable. You also import something called qttable which I can't find anywhere.  I'm pretty sure ParmFiddler and TableInspectory are not mission-critical but array_browser certainly is. Bleagh!

**Comment by twillis449** [comment]
Sigh - I don't have time to figure out this new authentication token stuff. When I do a git push it still asks me for a password. I'm leaving for a holiday till the end of September tomorrow AM. Anyway I'm attaching a tar file of my current PyApps directory.x-special/nautilus-clipboard
copy
file:///home/twillis/Documents/PyApps.tar.gz

**Comment by bennahugo** [comment]
Thanks @twillis449 I will push it and make a PR - it is as simple as using an ssh key to push by default

**Comment by twillis449** [comment]
Sounds like you're getting there :}
The current GUI would never work with current TByte+ sized visibility data sets in any case.

**Comment by bennahugo** [comment]
Ok this is fixed -- 
@twillis449 and @o-smirnov please note the install instructions have now changed quite substantially
https://github.com/ska-sa/meqtrees/wiki/BuildFromSource

Although you can muck with PYTHONPATH, LD_LIBRARY_PATH, and PATH as before I highly recommend that you just install this into a virtualenv.

**Comment by bennahugo** [comment]
I've asked @Athanaseus to release the pipeliner for Kern 7 and above as all the dependencies, including casarest now have packages on 20.04.
